### ISSUE TITLE
corrupt I/O with USB disk

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_kernel_5.10#16]
Originally reported by @rvs in a separate Fedora issue: https://github.com/starfive-tech/Fedora_on_StarFive/issues/27#issuecomment-830381873
> And if anyone is curious -- it indeed appears that reading from USB on my board with a stock Fedora kernel produces random results:
```
[root@fedora-starfive ~]# mount /dev/sda2 /mnt
[root@fedora-starfive ~]# md5sum /mnt/kernel-5.12.0+-1.riscv64.rpm
fdfdba4264bf7a0343b355cf51559b9f  /mnt/kernel-5.12.0+-1.riscv64.rpm
```
> AND if I plug it into a different USB socket:
```
[root@fedora-starfive ~]# mount /dev/sda2 /mnt
[root@fedora-starfive ~]# md5sum /mnt/kernel-5.12.0+-1.riscv64.rpm
cfa4ea2687344fbb2516637490fbb74b  /mnt/kernel-5.12.0+-1.riscv64.rpm
```
> And here's some more fun with this:
```
[root@fedora-starfive ~]# cd /root
[root@fedora-starfive ~]# cp /mnt/kernel-5.12.0+-1.riscv64.rpm 1
[root@fedora-starfive ~]# cp /mnt/kernel-5.12.0+-1.riscv64.rpm 2
[root@fedora-starfive ~]# cmp 1 2
1 2 differ: byte 442264320, line 1690479
```
> Welp, at least it copied quite a bit of bytes before garbage kicked in

**Comment by davidlt** [comment]
Isn't this fixed by https://github.com/esmil/linux/pull/10 ?
@pdp7 could you retest?

**Comment by rvs** [comment]
FWIW I haven't see it with his kernel @davidlt

**Comment by pdp7** [comment]
@stffrdhrn you tested and no longer had an issue with USB mass storage after https://github.com/starfive-tech/linux/commit/fbc58a5e93eb643834af2b543d29f605282067e2, correct?

It seemed like from your comment here that the USB disk is working ok:
https://github.com/starfive-tech/linux/issues/1#issuecomment-845778757

**Comment by stffrdhrn** [comment]
I never had a corruption issue. What kernel version was this for?

**Comment by esmil** [comment]
Just to make sure we're all talking about the same problem. My experience is that there is a big difference between USB 2.0 / high speed and USB 3.0 / super speed. USB 2.0 seems to work ok for me, but USB 3.0 devices are not detected when hotplugged and seems to work quite unreliably.

**Comment by pdp7** [comment]
@stffrdhrn that is good to hear, I think the issue that @rvs originally encountered was using the Fedora image from @tekkamanninja which has a 5.10 kernel.  So that is good to hear you have noticed no problem with the 5.13 kernel.

@esmil that is good to know about the issues with USB 3.0 super speed devices.  @MichaelZhuxx @tekkamanninja I believe there was mention awhile ago about how USB had a hotplug problem?

**Comment by pdp7** [comment]
I am going to close this but I will include a link to any new issues regarding USB disk
