### ISSUE TITLE
make 5.13 kernel the default branch

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_kernel_5.10#26]
@tekkamanninja There is not much value directing people to the 5.10 branch as the default ( https://github.com/starfive-tech/linux/tree/fedora-vic-7100_5.10.6).  I believe the only reason you are still using 5.10 is because Fedora 33 was 5.10?  Akira (@mcd500) has been repackaging the Fedora image to have the 5.13 kernel branch from @esmil and that is working well.

Now that @esmil can push directly to starfive-tech/linux/esmil_starlight and it stays in sync with esmil/linux/starlight I think it would make sense to make the default branch https://github.com/starfive-tech/linux/tree/esmil_starlight

Alternatively, a new branch such as `jh7100-5.13` could be created from `esmil_starlight` and could be made default `jh7100-5.13`

**Comment by esmil** [comment]
Yeah, if the starlight branch is made the default, let's call it something better than `esmil_starlight`. How about just `starlight` so it doesn't matter if you pull from github.com/starfive-tech/linux or github.com/esmil/linux, and it's just "the starlight branch".

I don't mind `jh7100-5.13` either. I'll just push to the starlight branch to that name until 5.14-rc1 is out and ill switch to `jh7100-5.14` and do `jh7100-5.13` like I'm doing starlight-5.12.y now.

**Comment by pdp7** [comment]
> Yeah, if the starlight branch is made the default, let's call it something better than `esmil_starlight`. How about just `starlight` so it doesn't matter if you pull from github.com/starfive-tech/linux or github.com/esmil/linux, and it's just "the starlight branch".
> 
> I don't mind `jh7100-5.13` either. I'll just push to the starlight branch to that name until 5.14-rc1 is out and ill switch to `jh7100-5.14` and do `jh7100-5.13` like I'm doing starlight-5.12.y now.

@esmil thanks for the comment.  Good point that soon we will have 5.14-rc1.  

**How about renaming `esmil_starlight` to `jh7100-devel` and making that the default?**

When we get ready to start rebasing for a proper patch series for git send-email, then 'jh7100-upstreaming' could be created from 'jh7100-devel'.

Regarding 'starlight', it would be best to avoid using that term on its own as 'beaglev-starlight' should be used instead.  However, that is a bit of a long string, so it might be best just to use the term jh7100 instead.  The exception being board specific term such as the board device tree where we will call that 'jh7100-beaglev-starlight'

**Comment by esmil** [comment]
jh7100-devel is fine by me. Alternatively we could call it just `beaglev`, so you check out the beaglev branch and do beaglev_defconfig etc. Thus postponing the naming problem until the beaglev-moonlight board comes out :-P

**Comment by pdp7** [comment]
@esmil I like your suggestion of beaglev as that is a simpler branch name than jh7100-devel.  The description can be that it is our downstream patches for the BeagleV Starlight JH7100 on top of the current mainline.

I created a new branch based on esmil_starlight:
https://github.com/starfive-tech/linux/tree/beaglev

If we all like that name, then I can start updating various links from 'esmil_starlight' to 'beaglev'.  We won't delete 'esmil_starlight' for awhile so it should give plenty of time to let people know they should update any configurations such as meta-riscv.

**Comment by esmil** [comment]
Cool. I'll just push to both `esmil_starlight` and `beaglev` next time then.

**Comment by esmil** [comment]
The defconfig is now also called `beaglev_defconfig` and it has `CONFIG_LOCALVERSION="-beaglev"`.
