### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by KwangSon** [starfive-tech/beagle_kernel_5.10#30]
Hi, I'm just follow beaglev linux kernel code for fun.
I hope I can find some place to contribute. (I'm not sure is there any mailing list? or github PR acceptable?)

I found typo
https://github.com/starfive-tech/linux/blob/6e86ec4e842c70a7d0d53dc600ac6742769b0d5f/arch/riscv/boot/dts/starfive/jh7100.dtsi#L366

nbdla -> nvdla

**Comment by esmil** [comment]
Thanks. There is nothing using this specifier, so it can just be deleted. That is just the `nbdla:` part can be removed, not the node itself of course.

There is no mailing list, but PRs are very welcome.

**Comment by KwangSon** [comment]
Yes it just alias, not important. but I'll create PR thanks!
