### ISSUE TITLE
bql?

### ISSUE THREAD

**Issue by dtaht** [starfive-tech/beagle_kernel_5.10#37]
What ethernet chip are y'all using? Does it have bql support?

**Comment by esmil** [comment]
I don't know, even had to google bql, but the JH7100 SoC has ethernet ip from designware using the stmmac Linux driver (CONFIG_DWMAC_GENERIC). The BeagleV Starlight boards has a Micrel KSZ9031 Gigabit PHY, and the new VisionFive V1 boards should have a "Motorcomm YT8521 Gigabit PHY".

I hope that's info you can use.

**Comment by dtaht** [comment]
thx for the info. But it's my hope that those that have the boards in front of them, take the time to put in the 6 lines of code required and to test. I outline those APIs in this document (originally for broadcom) here: 

http://www.taht.net/~d/broadcom_aug9_2018.pdf

**Comment by dtaht** [comment]
(I'm pulling down a current tree as I write to check) Is there anything in the queue that has two ethernet interfaces?

**Comment by dtaht** [comment]
ah, the fix landed long ago. Yay. fq_codel on in the build? 

I'm very interested in exploring what it will take to build a decent wifi router out of one of these things.

**Comment by esmil** [comment]
@dtaht The JH7100 SoC on the VisionFive V1 is basically a test chip for StarFive's upcoming JH7110 which should also have PCIe last I've heard. I don't know if there are any plans for more than one ethernet interface though.

As for making a wifi router out of this board I wouldn't use the onboard AP6236 module (broadcom chipset). It's connected through 50MHz 4bit SDIO. But with a decent USB3 wifi dongle it might work well.
For ethernet we still have a weird quirk where `stmmac.chain_mode=1` is needed on the kernel command line. I just think nobody has yet bothered to look into why that is needed. But @teknoraver was still able to get decent performance out of it I think.

**Comment by teknoraver** [comment]
Hi, I never tried to boot without `stmmac.chain_mode=1`. Anyway I was getting very decent performances, almost 1 gbit with 1500 byte packets
