### ISSUE TITLE
../include/linux/fortify-string.h:358:63: error: expected identifier or '(' before '{' token

### ISSUE THREAD

**Issue by andreas-schwab** [starfive-tech/beagle_kernel_5.10#53]
current visionfive branch doesn't compile:

  CC      arch/riscv/lib/string.o
In file included from ../include/linux/string.h:253,
                 from ../include/linux/bitmap.h:11,
                 from ../include/linux/cpumask.h:12,
                 from ../include/linux/mm_types_task.h:14,
                 from ../include/linux/mm_types.h:5,
                 from ../include/linux/buildid.h:5,
                 from ../include/linux/module.h:14,
                 from ../arch/riscv/lib/string.c:10:
../include/linux/fortify-string.h:358:63: error: expected identifier or '(' before '{' token
  358 |                              p_size_field, q_size_field, op) ({         \
      |                                                               ^
../include/linux/fortify-string.h:369:26: note: in expansion of macro '__fortify_memcpy_chk'
  369 | #define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                  \
      |                          ^~~~~~~~~~~~~~~~~~~~
../arch/riscv/lib/string.c:89:7: note: in expansion of macro 'memcpy'
   89 | void *memcpy(void *dest, const void *src, size_t count) __weak __alias(__memcpy);
      |       ^~~~~~
../include/linux/fortify-string.h:358:63: error: expected identifier or '(' before '{' token
  358 |                              p_size_field, q_size_field, op) ({         \
      |                                                               ^
../include/linux/fortify-string.h:373:27: note: in expansion of macro '__fortify_memcpy_chk'
  373 | #define memmove(p, q, s)  __fortify_memcpy_chk(p, q, s,                 \
      |                           ^~~~~~~~~~~~~~~~~~~~
../arch/riscv/lib/string.c:112:7: note: in expansion of macro 'memmove'
  112 | void *memmove(void *dest, const void *src, size_t count) __weak __alias(__memmove);
      |       ^~~~~~~
../include/linux/fortify-string.h:262:65: error: expected identifier or '(' before '{' token
  262 | #define __fortify_memset_chk(p, c, size, p_size, p_size_field) ({       \
      |                                                                 ^
../include/linux/fortify-string.h:272:25: note: in expansion of macro '__fortify_memset_chk'
  272 | #define memset(p, c, s) __fortify_memset_chk(p, c, s,                   \
      |                         ^~~~~~~~~~~~~~~~~~~~
../arch/riscv/lib/string.c:153:7: note: in expansion of macro 'memset'
  153 | void *memset(void *s, int c, size_t count) __weak __alias(__memset);
      |       ^~~~~~
make[1]: *** [../scripts/Makefile.build:289: arch/riscv/lib/string.o] Error 1

**Comment by esmil** [comment]
I just rebased the visionfive branch on v5.18-rc2 and added `#undef`s to hopefully fix this.
@teknoraver I wonder if it soon time to drop these patches :/

**Comment by teknoraver** [comment]
the problem is only with fortify headers?

**Comment by esmil** [comment]
Yeah, I've fixed this specific problem by adding `#undef memcpy` etc. before their definitions to undo the macros in fortify-string.h.
https://github.com/starfive-tech/linux/commit/c190425d9c3f4b59571b66ed15993d0868df6124#diff-f941e12d5e8b6cfb6a58bec6cdeb94be4cc7b535297ad23ba97605e9dc2b4dafR89

I was just wondering if you'd given up working on these patches. If you haven't I don't mind keeping them in this branch, but if you have then it'd be a waste to keep updating them.

**Comment by teknoraver** [comment]
I think we should push them into mainline

**Comment by andreas-schwab** [comment]
I think the right fix is to #define __NO_FORTIFY in arch/riscv/lib/string.c, like lib/string.c (as in commit cfecea6ead5f).
