### ISSUE TITLE
make[2]: *** No rule to make target 'arch/riscv/lib/memcpy.S', needed by 'arch/riscv/purgatory/memcpy.o'.  Stop.

### ISSUE THREAD

**Issue by andreas-schwab** [starfive-tech/beagle_kernel_5.10#59]
When enabling CONFIG_KEXEC_FILE, which implies CONFIG_ARCH_HAS_KEXEC_PURGATORY, build fails in arch/riscv/purgatory.

**Comment by esmil** [comment]
Hi Andreas, thanks for the report. I just pushed a fix to the visionfive branch that at least makes the purgatory build for me. I intend to merge it into the memcpy/memset patches when I rebase on rc3.

**Comment by andreas-schwab** [comment]
Thanks, works here too.
