### ISSUE TITLE
It may cause problem during compiling

### ISSUE THREAD

**Issue by CharlieYu4994** [starfive-tech/beagle_kernel_5.10#60]
https://github.com/starfive-tech/linux/blob/dbbb7f54df7d17b2a774ed04500d5a19d415cc22/arch/riscv/configs/starfive_jh7100_fedora_defconfig#L19
I can't finish compiling the kernel with this option which causes Error 127 during compiling

**Comment by esmil** [comment]
@tekkamanninja Do you have an opinion on this or maybe an update to the fedora defconfig?
