### ISSUE TITLE
error: implicit declaration of function 'sifive_l2_flush64_range'

### ISSUE THREAD

**Issue by andreas-schwab** [starfive-tech/beagle_kernel_5.10#63]
CC      drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.o
../drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.c: In function 'dw_dma_async_do_memcpy':
../drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.c:179:9: error: implicit declaration of function 'sifive_l2_flush64_range'; did you mean 'sifive_l2_flush_range'? [-Werror=implicit-function-declaration]
  179 |         sifive_l2_flush64_range(src_dma, size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         sifive_l2_flush_range
cc1: some warnings being treated as errors
make[3]: *** [../scripts/Makefile.build:250: drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.o] Error 1
make[2]: *** [../scripts/Makefile.build:467: drivers/dma/dw-axi-dmac-starfive] Error 2
make[1]: *** [../scripts/Makefile.build:467: drivers/dma] Error 2

**Comment by esmil** [comment]
Sorry, I should probably have deleted this code a long time ago. Nothing actually uses any of the code in `drivers/dma/dw-axi-dmac-starfive/`. But now it should at least compile again..

**Comment by andreas-schwab** [comment]
Fixed with 575362a88f9e.
