### ISSUE TITLE
modpost errors

### ISSUE THREAD

**Issue by andreas-schwab** [starfive-tech/beagle_kernel_5.10#64]
ERROR: modpost: missing MODULE_LICENSE() in drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.o
ERROR: modpost: "arch_setup_dma_ops" [drivers/dma/dw-axi-dmac-starfive/starfive_dmaengine_memcpy.ko] undefined!

**Comment by esmil** [comment]
Ok, with this and https://lore.kernel.org/all/202207071751.cBaGYxUU-lkp@intel.com/ I think it's time to just delete this unused code. Let me know if you disagree.

**Comment by esmil** [comment]
Ok, removed in the latest visionfive branch.
