### ISSUE TITLE
Kernel version Linux buildroot 5.15.0-dirty 

### ISSUE THREAD

**Issue by dtometzki** [starfive-tech/beagle_kernel_5.10#70]
Hello together,

where i can find the extension dirty in the SDK ?

I would remove it

Damian

**Comment by RevySR** [comment]
https://github.com/starfive-tech/buildroot/blob/JH7110_VisionFive2_devel/linux/linux.mk#L264

CONFIG_LOCALVERSION_AUTO=y and patch applied

the extension dirty is shown

**Comment by dtometzki** [comment]
Great it works
