### ISSUE TITLE
branch reorganization and cleanup

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_kernel_5.10#9]
@tekkamanninja please reorganize this repository so that:
- [x] ` starfive-tech/linux/master` from torvalds/linux.git/master 
  * this is currently 5.13-rc1
- [x] replace `starfive-tech/linux/Fedora` with `starfive-tech/linux/fedora-vic-7100_5.10.6` and make it default
  * currently this is 5.10
- [x] create `starfive-tech/linux/esmil-starlight` from @esmil branch https://github.com/esmil/linux/tree/starlight

**Comment by pdp7** [comment]
@tekkamanninja for reorg of repos:
* starfive-tech/linux/master -> kernel.org/linux.git/master 
* starfive-tech/linux/starfive-devel [5.12] -> kernel.org/linux.git/master [5.12] + starfive patches?
* starfive-tech/linux/Fedora [5.10] -> starfive-tech/linux/fedora-rpm-devel  [5.10]
* 5.12 branch by @esmil https://github.com/esmil/linux/tree/starlight -> starfive-tech/linux/esmil-starlight?

**Comment by pdp7** [comment]
@tekkamanninja  please pull in 5.13-rc3 from @geertu into branch in starfive-tech linux 
https://github.com/geertu/linux/tree/starlight-v5.13-rc1

here is the slack thread for reference:
https://beagleboard.slack.com/archives/C01QV90F5KM/p1620746063146400

**Comment by pdp7** [comment]
@tekkamanninja 

current plan look ok?

1) pull in the new 5.13-rc2 https://github.com/esmil/linux/tree/starlight into https://github.com/starfive-tech/linux/tree/esmil_starlight

2) copy 5.13-rc2 https://github.com/starfive-tech/linux/tree/esmil_starlight to new branch https://github.com/starfive-tech/linux/tree/jh7100-upstreaming

3) use jh7100-upstreaming for git send-email

**Comment by geertu** [comment]
> @tekkamanninja
> 
> current plan look ok?
> 
> 1. pull in the new 5.13-rc2 https://github.com/esmil/linux/tree/starlight into https://github.com/starfive-tech/linux/tree/esmil_starlight
> 2. copy 5.13-rc2 https://github.com/starfive-tech/linux/tree/esmil_starlight to new branch https://github.com/starfive-tech/linux/tree/jh7100-upstreaming
> 3. use jh7100-upstreaming for git send-email

Lots of commits lack Signed-off-by tags.
Don't forget to run scripts/checkpatch.pl before posting patches, so individual reviewers don't have to point out all issues detected.

**Comment by pdp7** [comment]
_FYI - I have edited the original issue description_

The important branches are now:
* https://github.com/starfive-tech/linux/tree/fedora-vic-7100_5.10.6 which is used for @tekkamanninja [Fedora image](https://github.com/starfive-tech/Fedora_on_StarFive)
* https://github.com/starfive-tech/linux/tree/master is `torvalds/linux/master`
* https://github.com/starfive-tech/linux/tree/esmil_starlight is now pushed directly by @esmil 

TODO for @MichaelZhuxx or @tekkamanninja:
- [x] remove the old Fedora branch: https://github.com/starfive-tech/linux/tree/Fedora
- [x] remove the old starfive branch: https://github.com/starfive-tech/linux/commits/starfive
- [ ] create `jh7100-upstreaming` branch from https://github.com/starfive-tech/linux/tree/esmil_starlight ?
  - use this branch reorganize commits to prepare for sending patch series to kernel mailing lists

**Comment by pdp7** [comment]
@MichaelZhuxx please delete the `main` branch as it is not used https://github.com/starfive-tech/linux/tree/main

**Comment by MichaelZhuxx** [comment]
> @MichaelZhuxx please delete the `main` branch as it is not used https://github.com/starfive-tech/linux/tree/main

Sure, Done
